tasks:
  - init: git remote set-url origin git@github.com:tina-rev/tina-rev-pep-project.git && sed "s/\r$//" commit-command.sh | bash
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - revaturePro.revature-labs